version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - .env
    volumes:
      - ./pokecertify:/app
    ports:
      - "8000:8000"
    depends_on:
      - modal
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    env_file:
      - .env
    volumes:
      - ./pokecertify:/app
    ports:
      - "7860:7860"
    depends_on:
      - backend
    restart: unless-stopped

  # Modal Labs is a managed service, but you may want a placeholder for local dev
  modal:
    image: alpine:3.18
    command: ["sh", "-c", "echo 'Modal Labs runs in the cloud. This is a placeholder.' && sleep 3600"]
    restart: unless-stopped

# Optional: add a db service if you migrate to PostgreSQL in the future

networks:
  default:
    driver: bridge